language: node
services:
  - docker
before_install:
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  # Use either `docker-compose` or individual `docker build` commands
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  # Do similar for other three images

  # Tagging
  - docker tag udagram-api-feed dinhtin12/udagram-api-feed:v2
  # Do similar for other three images

  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dinhtin12/udagram-api-feed:v2
  # Do similar for other three images

  # user
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user dinhtin12/udagram-api-user:v2
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dinhtin12/udagram-api-user:v2

  # frontend
  - docker build -t udagram-api-frontend ./udagram-api-frontend
  - docker tag udagram-api-frontend dinhtin12/udagram-api-frontend:v2
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dinhtin12/udagram-api-frontend:v2

  # reverseproxy
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy dinhtin12/udagram-reverseproxy:v2
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dinhtin12/udagram-api-frontend:v2
