language: node
services:
  - docker
before_install:
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
  # Use either `docker-compose` or individual `docker build` commands
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  # Do similar for other three images

  # Tagging
  - docker tag udagram-api-feed dinhtin12/udagram-api-feed:v5
  # Do similar for other three images

  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push dinhtin12/udagram-api-feed:v5

script: npm test
  # Do similar for other three images

  # # user
  # - docker build -t udagram-api-user ./udagram-api-user
  # - docker tag udagram-api-user dinhtin12/udagram-api-user:v5
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push dinhtin12/udagram-api-user:v5

  # # frontend
  # - docker build -t udagram-frontend ./udagram-frontend
  # - docker tag udagram-frontend dinhtin12/udagram-frontend:v5
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push dinhtin12/udagram-frontend:v5

  # # reverseproxy
  # - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  # - docker tag udagram-reverseproxy dinhtin12/udagram-reverseproxy:v5
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push dinhtin12/udagram-reverseproxy:v5
